language: haskell

ghc:
  - "8.8.4"

env:
  - PATH=${HOME}/.cabal/bin:${PATH}

before_install:
  - travis_retry sudo apt-get update

install:
  - travis_retry cabal install alex happy
  - travis_retry cabal install --enable-tests --only-dependencies ogma-**/

script:
  # We want to document the build process, and  get detailed information if
  # there is a problem (or if all goes well). We therefore execute the
  # installation with -j1.
  #
  # Some tests need the ogma executable to be in the path, which won't happen
  # until installation completes successfully (which only happens after tests
  # if running tests is enabled). We therefore need to run the installation
  # twice: once without --run-tests, and again with --run-tests.
  #
  # We still --enable-tests in the first compilation to make sure that the
  # dependencies do not change and cabal does not change the installation plan
  # (which would mean we'd be running the tests with a version of ogma compiled
  # with different dependencies).
  - cabal install --enable-tests -j1 ogma-**/
  - cabal install --run-tests -j1 ogma-**/

after_script:

branches:
    only:
          - master
          - /^develop.*$/
          - /^hotfix.*$/
          - /^release.*$/
